apiVersion: apps/v1
kind: Deployment
metadata:
  name: piece-detector
spec:
  selector:
    matchLabels:
      app: piece-detector
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: piece-detector
    spec:
      containers:
      - name: piece-detector
        image: jethibau/piece-detector
        volumeMounts:
        - mountPath: /dev/video0
          name: dev-video0
        - mountPath: /final/images
          name: image-repo
        securityContext:
          privileged: true
      volumes:
      - name: dev-video0
        hostPath:
          path: /dev/video0
      - name: image-repo
        hostPath:
          path: /final/images