apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-processor
spec:
  selector:
    matchLabels:
      app: image-processor
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: image-processor
    spec:
      containers:
      - name: image-processor
        image: jethibau/hw3-image-processor
        volumeMounts:
          - name: creds
            mountPath: /.aws
      volumes:
        - name: creds
          hostPath:
            path: /home/ubuntu/.aws