apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-logger
spec:
  selector:
    matchLabels:
      app: message-logger
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: message-logger
    spec:
      containers:
      - name: message-logger
        image: jethibau/hw3-edge-message-logger