apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  labels:
    run: mosquitto
spec:
  ports:
  - name: image-processor
    port: 1883
    nodePort: 31801
    targetPort: 1883
    protocol: TCP
  selector:
    app: mosquitto