apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  labels:
    run: mosquitto
spec:
  type: NodePort
  ports:
  - name: image-processor
    nodePort: 32000
    port: 1883
    protocol: TCP
    targetPort: 1883
  selector:
    app: mosquitto